name: abidkhan
description: My portfolio using Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: AgencyFB
      fonts:
        - asset: assets/agency-fb.ttf
        
